name: pip-tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
        exclude:
          - os: macos-latest
            python-version: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/checkout@v2.7.0
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pymapf
      - name: Checkout reposistory
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest
